{"name": "test_login_with_valid_credentials", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n  +403\n  -200", "trace": "api_client = <utils.api_client.APIClient object at 0x00000182FE961E50>\nuser_data = {'email': 'testuser@example.com', 'name': 'Test User', 'password': 'password123'}\n\n    @pytest.fixture(scope=\"session\")\n    def ensure_user_created(api_client, user_data):\n        \"\"\"Фикстура для регистрации пользователя\"\"\"\n        response = api_client.register_user(user_data)\n>       assert response.status_code == 200\nE       assert 403 == 200\nE         +403\nE         -200\n\ntests\\conftest.py:26: AssertionError"}, "description": "Тест для успешной авторизации с правильными данными пользователя", "start": 1744991683059, "stop": 1744991683059, "uuid": "7085a679-8ee9-4a46-8adf-ae13cf4c1329", "historyId": "8b84f6137dd792b9a8e19e5cb95fdd25", "testCaseId": "8b84f6137dd792b9a8e19e5cb95fdd25", "fullName": "tests.test_login#test_login_with_valid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-U9HTL48"}, {"name": "thread", "value": "39648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}